rules:
  - id: general
    description: 一般ルームではメンション時のみ応答
    examples: ["@カレン 明日の予定教えて"]
    priority: 1
  - id: bot_room
    description: bot専用ルームでは全発言に応答
    examples: ["明日14時に会議入れて"]
    priority: 2 